[dataset]
path = "data/spx_eod_202301.csv"
date = "2023-01-04"
tmin = 0.01
tmax = 2.0
min_bid = 0.05
kq_lo = 0.02
kq_hi = 0.98

[market]
S0 = 3853.39
r  = 0.04974181812769106
q  = 0.023177742794908366

[train]
epochs = 120
lr = 0.0005
width = 128
hidden = 4
INT_N = 4096
batch_int = 4096
batch_mkt = 2048
sigma_ref = 0.25
lam_sigma = 0.0005
lam_pos   = 0.0005
lam_tie   = 0.002
w_pde = 0.02
w_mkt = 1.0
w_arb = 0.02
w_bc  = 0.10
w_reg1 = 1e-05
w_reg2 = 0.0
w_mass = 0.0
mass_nx = 256
mass_nt = 12
resume = false
al = false
eta = 0.5

[eval]
nx = 128
nt = 64
eps = 1e-6

[gate]
q_lo = 0.02
q_hi = 0.98
max_nv = 20
max_resid = 0.02
max_mass = 0.03
max_rmse_rel = 0.008

[visualize]
nx = 200
nt = 100

[output]
root = "processed"
run_name = "spx_cli_parity"
use_ckpt = "ckpt.pt"

